version: '3.9'

services:
  db:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--port", "6388"]
    ports:
      - "6388:6388"
    volumes:
      - redis-data:/data

  web:
    build: .
    container_name: django
    command: daphne -b 0.0.0.0 -p 8001 test_redis.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - REDIS_HOST=db
      - REDIS_PORT=6388

volumes:
  redis-data:
